export const types = {
  DEFAULT: 'DEFAULT',
  SET_SETTINGS: 'SET_SETTINGS',
  GET_SETTINGS: 'GET_SETTINGS',
  SET_BETS: 'SET_BETS',
  GET_BETS: 'GET_BETS',
  SET_GAMES: 'SET_GAMES',
  GET_GAMES: 'GET_GAMES',
  SET_GAME: 'SET_GAME',
  GET_GAME: 'GET_GAME'
}
