export const types = {
  DEFAULT: 'DEFAULT',
  SET_CONFIG: 'SET_CONFIG',
  GET_CONFIG: 'GET_CONFIG',
  SET_SETTINGS: 'SET_SETTINGS',
  GET_SETTINGS: 'GET_SETTINGS',
  SET_BETS: 'SET_BETS',
  GET_BETS: 'GET_BETS',
  SET_GAMES: 'SET_GAMES',
  GET_GAMES: 'GET_GAMES',
  SET_GAME: 'SET_GAME',
  GET_GAME: 'GET_GAME',
  SET_TOASTIFY: 'SET_TOASTIFY',
  GET_TOASTIFY: 'GET_TOASTIFY'
}
